// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSufQLKlazTwQXz_W5nvGBh8bvCXkJdhg',
    appId: '1:18943098158:web:ab36f45179ba419c304ebf',
    messagingSenderId: '18943098158',
    projectId: 'savesmart-63f96',
    authDomain: 'savesmart-63f96.firebaseapp.com',
    storageBucket: 'savesmart-63f96.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsCwfuL3AJbkH06C50yZlP-xwg_L2cxZI',
    appId: '1:18943098158:android:0f86ab8009b24360304ebf',
    messagingSenderId: '18943098158',
    projectId: 'savesmart-63f96',
    storageBucket: 'savesmart-63f96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtA_0b1gndehvAIGWKLuA67hjHWBriEJ4',
    appId: '1:18943098158:ios:b66acaf41cba747a304ebf',
    messagingSenderId: '18943098158',
    projectId: 'savesmart-63f96',
    storageBucket: 'savesmart-63f96.firebasestorage.app',
    iosBundleId: 'com.example.savesmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtA_0b1gndehvAIGWKLuA67hjHWBriEJ4',
    appId: '1:18943098158:ios:b66acaf41cba747a304ebf',
    messagingSenderId: '18943098158',
    projectId: 'savesmart-63f96',
    storageBucket: 'savesmart-63f96.firebasestorage.app',
    iosBundleId: 'com.example.savesmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSufQLKlazTwQXz_W5nvGBh8bvCXkJdhg',
    appId: '1:18943098158:web:a6cb296f7a34090e304ebf',
    messagingSenderId: '18943098158',
    projectId: 'savesmart-63f96',
    authDomain: 'savesmart-63f96.firebaseapp.com',
    storageBucket: 'savesmart-63f96.firebasestorage.app',
  );
}
